---
run:
  timeout: 300s
  skip-dirs:
    - "^tools/"
  build-tags:
    - tests

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/cerbos/cerbos)
      - blank
      - dot
    skip-generated: true
    custom-order: true

  goheader:
    values:
      const:
        COMPANY: Zenauth Ltd.
    template: |-
      Copyright {{ YEAR-RANGE }} {{ COMPANY }}
      SPDX-License-Identifier: Apache-2.0

  govet:
    enable-all: true
    disable:
      - shadow

  nolintlint:
    allow-unused: true # false would be preferable, but it's flaky (https://github.com/golangci/golangci-lint/issues/3228)
    allow-leading-space: false
    require-specific: true

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert
    - goconst
    - gocritic
    - goimports
    - goheader
    - gomnd
    - gomoddirectives
    - gosec
    - govet
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

issues:
  max-same-issues: 30

  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - forcetypeassert
        - goconst
        - gomnd
        - govet
