version: "2"
run:
  build-tags:
    - tests
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - goconst
    - gocritic
    - goheader
    - gomoddirectives
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unparam
    - wastedassign
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    goheader:
      values:
        const:
          COMPANY: Zenauth Ltd.
      template: |-
        Copyright {{ YEAR-RANGE }} {{ COMPANY }}
        SPDX-License-Identifier: Apache-2.0
    govet:
      disable:
        - shadow
      enable-all: true
    nolintlint:
      require-specific: true
      allow-unused: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - forcetypeassert
          - goconst
          - govet
          - mnd
        path: _test\.go
    paths:
      - ^tools/
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 30
formatters:
  enable:
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/cerbos/cerbos)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - ^tools/
      - third_party$
      - builtin$
      - examples$
