name: Set up Go

description: Install Go and Spitfire dependencies

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
        check-latest: true
        cache: true
