---
name: CI
on:
  pull_request:
    branches:
      - main
      - 'v*'
permissions:
  contents: read

jobs:
  test:
    name: PR test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Install Go
      uses: ./.github/actions/setup-go

    - name: Lint GitHub Actions
      run: go tool github.com/rhysd/actionlint/cmd/actionlint

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8.0.0
      with:
        version: latest
        args: '--config=.golangci.yaml -v'

    - name: Test
      run: go test ./...

    - name: Upload JUnit reports
      uses: actions/upload-artifact@v4
      with:
        name: junit-reports-${{ strategy.job-index }}
        path: junit.*.xml

    - name: Upload to CodeCov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: "unit.cover,integration.cover"

