---
name: Release
on:
  push:
    tags:
      - v*
permissions:
  contents: write
  issues: write
  # packages: write
  # id-token: write

jobs:
  releaseBinaries:
    name: Release Binaries
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: ./.github/actions/setup-go

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --config=.goreleaser.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

