---
name: Release
on:
  push:
    tags:
      - v*
permissions:
  contents: write
  issues: write
  # packages: write
  # id-token: write

jobs:
  releaseBinaries:
    name: Release Binaries
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Go
        uses: ./.github/actions/setup-go

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a
        with:
          version: latest
          args: release --config=.goreleaser.yml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

