---
name: Vulnerability Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1,3,5'
permissions:
  contents: read

jobs:
  runVulnerabilityCheck:
    name: Run Vulnerability Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: ./.github/actions/setup-go

      - name: Check vulnerabilities
        run: |
          go tool golang.org/x/vuln/cmd/govulncheck -v ./...
