---
name: Vulnerability Check
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1,3,5'
jobs:
  runVulnerabilityCheck:
    name: Run Vulnerability Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go and restore cached dependencies
        uses: ./.github/actions/setup-go

      - name: Check vulnerabilities
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -v ./...
